# Generated by Django 5.2.7 on 2025-10-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlJourney', '0002_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobby',
            name='profile',
        ),
        migrations.AlterField(
            model_name='hobby',
            name='description',
            field=models.TextField(),
        ),
    ]
