# Generated by Django 5.2.7 on 2025-10-25 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tlJourney', '0003_remove_hobby_profile_alter_hobby_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Year',
        ),
    ]
